name: Renew Credentials

on:
  workflow_dispatch:
  schedule:
    # Run every five day at midnight.
    - cron: '0 0 */5 * *'

jobs:
  renew:
    name: Renew credentials
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v6
        with:
          version: ^11.6.0
          run_install: true
      - env:
          TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
          TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
          TEST_REFRESH_TOKEN: ${{ secrets.TEST_REFRESH_TOKEN }}
        run: pnpm ci-renew-credentials
